cmdargs:
  # Checking more strictly
  severity: style_problem

  # Enable coloring
  color: true

  # Enable Neovim syntax
  env:
    neovim: true

skip_paths:
  - tests/
  - doc/
#policies:
  # Disable a violation
  #ProhibitSomethingEvil:
  #  enabled: true

  # Enable a violation
  #  ProhibitSomethingBad:
  #  enabled: false
