
ck = [
    [
        [], "
            (
                common_block
                |
                (
                    table_options
                    |
                    (
                        CHAIN chain_identifier chain_block_alloc
                        '{' 
                            chain_block
                            |
                            SET set_identifier set_block_alloc
                            '{'
                                set_block
                                                                                                                                                                                                                                                                                                |
                                                                                                                                                                                                                                                                                                                        MAP set_identifier map_block_alloc
                                                                                                                                                                                                                                                                                                                                                '{' map_block
                                                                                                                                                                                                                                                                                                                                                                        |
                                                                                                                                                                                                                                                                                                                                                                                                FLOWTABLE flowtable_identifier flowtable_block_alloc
                                                                                                                                                                                                                                                                                                                                                                                                                        '{'
                                                                                                                                                                                                                                                                                                                                                                                                                                                    flowtable_block
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                '}'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )?
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                stmt_separator|
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        COUNTER obj_identifier obj_block_alloc
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                '{'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            counter_block
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    '}'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            stmt_separator close_scope_counter|
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    QUOTA obj_identifier obj_block_alloc
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            '{'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        quota_block
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                '}'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        stmt_separator close_scope_quota|
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                CT (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            HELPER obj_identifier obj_block_alloc '{'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ct_helper_block|
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        TIMEOUT obj_identifier obj_block_alloc '{'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ct_timeout_block|
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    EXPECTATION obj_identifier obj_block_alloc'{'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ct_expect_block)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            '}'stmt_separator close_scope_ct|
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    LIMIT obj_identifier obj_block_alloc'{'limit_block'}'stmt_separatorclose_scope_limit|SECMARKobj_identifierobj_block_alloc'{'secmark_block'}'stmt_separatorclose_scope_secmark|SYNPROXYobj_identifierobj_block_alloc'{'synproxy_block'}'stmt_separatorclose_scope_synproxy
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )*"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ]
            ]
